import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import { apiUrl } from './api/url'
import { useRandomNumber } from '../hooks/useRandomNumber'

import styles from './../styles/index.module.css'

export default function Home() {
  const [character, setCharacter] = useState(null)
  const [error, setError] = useState(null)
  const [isPending, setIsPending] = useState(false)

  const characterId = useRandomNumber(1,826)

  const loader = () => {
    return `${apiUrl}/avatar/${characterId}.jpeg`
  }

  const handleClick = async (id) => {
    try {
      id = characterId

      setError(false)
      setIsPending(true)
      setCharacter(null)

      const response = await fetch(`${apiUrl}${id}`)
      const jsonResponse = await response.json()

      setIsPending(false)
      setCharacter(jsonResponse)
    } catch (error) {
      setError(error)
      setIsPending(false)
      setCharacter(null)
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Random Rick and Morty characters!</h1>
        <button
          onClick={handleClick}
          className={styles['button']}
        >
          Show random character
        </button>
        { error && <p>{error}</p> }
        { isPending && <p>Loading...</p> }
          { character &&
            <section className={styles.character}>
              <Image
                loader={loader}
                src={character.image}
                alt="Character's image"
                width="300"
                height="300"
                className={styles.image}
              />
              <h2>Name: {character.name}</h2>
              <p>Gender: {character.gender}</p>
              <p>Type: {character.type}</p>
              <p>Species: {character.species}</p>
              <p>Status: {character.status}</p>
              <p>Id: {character.id}</p>
            </section>
          }
      </main>
    </div>
  )
}
